version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build react app
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: build
          prefix: build

  trigger-wrapper-build-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Trigger build-deploy in excel-add-in-private
          command: |
            curl -X POST https://circleci.com/api/v2/project/github/datadotworld/excel-add-in-private/pipeline \
              -H "Circle-Token: $CIRCLE_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{"branch":"main"}'

workflows:
  build:
    jobs:
      - build

      - trigger-wrapper-build-deploy:
          filters:
            branches:
              only:
                - main
