version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build react app
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: build
          prefix: build

workflows:
  build:
    jobs:
      - build
